INSERT INTO ATTENDEE(FIRST_NAME, LAST_NAME)
VALUES('Jon', 'Doe');

SELECT * FROM ATTENDEE;

INSERT INTO ATTENDEE(FIRST_NAME, LAST_NAME, PHONE, EMAIL, VIP)
VALUES
('Jon', 'Skeeter', '4891231234', 'jon.skeeter@rex.net', 1),
('Sam', 'Scala', '3541231234', 'sam.scala@gmail.com', 0),
('Brittany', 'Fisher', '4897566578', 'brittany.fisher@outlook.com', 0);

INSERT INTO ATTENDEE(FIRST_NAME, LAST_NAME, PHONE, EMAIL, VIP)
SELECT FIRST_NAME, LAST_NAME, PHONE, EMAIL, VIP
FROM SOME_OTHER_TABLE;

INSERT INTO COMPANY(NAME, DESCRIPTION, PRIMARY_CONTACT_ID)
VALUES ('RexApp Solutions', 'A mobile app delivery service', 3);

-- TRUNCATE TABLE ATTENDEE;

UPDATE ATTENDEE SET EMAIL = upper(EMAIL);

UPDATE ATTENDEE SET 
FIRST_NAME = upper(FIRST_NAME),
LAST_NAME = upper(LAST_NAME);

UPDATE ATTENDEE SET VIP = 1
WHERE ATTENDEE_ID IN (3,4);

DROP TABLE MY_UNWANTED_TABLE;