SELECT
    ORDER_ID,
    CUSTOMER.CUSTOMER_ID,
    ORDER_DATE,
    SHIP_DATE,
    NAME,
    STREET_ADDRESS,
    CITY,
    STATE,
    ZIP,
    PRODUCT_ID,
    ORDER_QTY
FROM CUSTOMER
INNER JOIN CUSTOMER_ORDER
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;

SELECT
    ORDER_ID,
    CUSTOMER.CUSTOMER_ID,
    ORDER_DATE,
    SHIP_DATE,
    NAME,
    STREET_ADDRESS,
    CITY,
    STATE,
    ZIP,
    PRODUCT_ID,
    ORDER_QTY
FROM CUSTOMER LEFT JOIN CUSTOMER_ORDER
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;

SELECT
    CUSTOMER.CUSTOMER_ID,
    NAME AS CUSTOMER_NAME
FROM CUSTOMER LEFT JOIN CUSTOMER_ORDER
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
WHERE ORDER_ID IS NULL;

SELECT
    CUSTOMER.CUSTOMER_ID,
    NAME AS CUSTOMER_NAME
FROM CUSTOMER OUTER JOIN CUSTOMER_ORDER
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;

SELECT
    CUSTOMER.CUSTOMER_ID,
    NAME AS CUSTOMER_NAME
FROM CUSTOMER RIGHT JOIN CUSTOMER_ORDER
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;

SELECT
    ORDER_ID,
    CUSTOMER.CUSTOMER_ID,
    ORDER_DATE,
    SHIP_DATE,
    NAME AS CUSTOMER_NAME,
    STREET_ADDRESS,
    CITY,
    STATE,
    ZIP,
    ORDER_DATE,
    PRODUCT.PRODUCT_ID,
    DESCRIPTION,
    ORDER_QTY,
    ORDER_QTY * PRICE AS REVENUE
FROM CUSTOMER INNER JOIN CUSTOMER_ORDER
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
INNER JOIN PRODUCT 
ON CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID;

SELECT
    CUSTOMER.CUSTOMER_ID,
    NAME AS CUSTOMER_NAME,
    sum(ORDER_QTY * PRICE) AS TOTAL_REVENUE
FROM CUSTOMER LEFT JOIN CUSTOMER_ORDER
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
LEFT JOIN PRODUCT 
ON CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY 1, 2;

SELECT
    CUSTOMER.CUSTOMER_ID,
    NAME AS CUSTOMER_NAME,
    coalesce(sum(ORDER_QTY * PRICE), 0) AS TOTAL_REVENUE
FROM CUSTOMER LEFT JOIN CUSTOMER_ORDER
ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
LEFT JOIN PRODUCT 
ON CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY 1, 2;